### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by RoelVdP** [Percona-QA/pstress#9]
I would appreciate if a copy of the "Contributors" from this page; 
https://github.com/Percona-QA/pquery
Was added to the end of the README 
AND to also add the file CONTRIBUTORS back from there:
https://github.com/Percona-QA/pquery/blob/master/doc/CONTRIBUTORS
Feel free to add to both lists, without removing anything already there.
This will duly acknowledge all previous people who worked on this code besides new developers.
Thank you for starting a new project based on the previous ones.

**Comment by rahulmalik87** [comment]
thanks, @RoelVdP.  we have restored the contributor list

**Comment by mariadb-RoelVandePaar** [comment]
Thank you
